#kafka.bootstrap-servers=localhost:29092
kafka.bootstrap-servers=b-1.pythagtestmsk.py1kdn.c2.kafka.us-east-2.amazonaws.com:9092
#spring.kafka.bootstrap-servers=b-1.pythagtestmsk.py1kdn.c2.kafka.us-east-2.amazonaws.com:9092

spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.group-id=order-transactions

