# Set cookie max age (in seconds). Example: 7 days (604800 seconds)
#server.servlet.session.cookie.max-age=604800

# Optionally, specify session timeout (in seconds)
#server.servlet.session.timeout=500
#server.servlet.session.cookie.http-only=true